export interface TemplateDefinition {
  id: string;
  title: string;
  description: string;
  category:
    | "Quotes"
    | "Reviews"
    | "Announcements"
    | "Milestones"
    | "Photo Collage"
    | "Carousel"
    | "Polls"
    | "Job Posts"
    | "Tips & Threads";
  domainRecommended?: string[];
  defaultData: Record<string, any>;
  colorPalettes: Array<{
    id: string;
    name: string;
    bg: string;
    text: string;
    accent: string;
    border: string;
    subBg?: string;
  }>;
}

export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  {
    id: "pull-quote",
    title: "Pull-Quote Card",
    description: "Large italic editorial serif quote with author attribution and citation deck.",
    category: "Quotes",
    domainRecommended: ["Software Engineering", "Design", "Product"],
    defaultData: {
      quote: "Design is not just what it looks like and feels like. Design is how it works.",
      author: "Steve Jobs",
      role: "Co-founder & CEO",
      organization: "Apple Inc.",
      citation: "Issue #44 // Reflections on Craft",
      themeVariant: "palette-1",
      fontPairing: "serif",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Terracotta Paper",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
        subBg: "bg-[#EDE6DA]",
      },
      {
        id: "palette-2",
        name: "Cobalt Electric",
        bg: "bg-[#1F4BD8]",
        text: "text-[#F6EFD9]",
        accent: "text-[#9CC4F2]",
        border: "border-[#9CC4F2]/30",
        subBg: "bg-[#0B1F66]",
      },
      {
        id: "palette-3",
        name: "Midnight Amber",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
        subBg: "bg-[#0E0F14]",
      },
    ],
  },
  {
    id: "book-review",
    title: "Book & Article Review",
    description: "Editorial 'REVIEW' layout with star rating, thumbnail cover, and 3-line verdict.",
    category: "Reviews",
    domainRecommended: ["Design", "Product", "Data & AI"],
    defaultData: {
      tag: "EDITORIAL REVIEW",
      title: "The Design of Everyday Things",
      author: "Don Norman",
      rating: 5,
      verdict: "Essential reading for anyone creating human-centric tools. Changed how I see door handles and complex software alike.",
      takeaway1: "Affordances clarify intuitive interactions.",
      takeaway2: "Feedback loops reduce cognitive errors.",
      coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Editorial Warm",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Olive Scholar",
        bg: "bg-[#F5F7F0]",
        text: "text-[#1F2618]",
        accent: "text-[#6F7B4A]",
        border: "border-[#C8D1BE]",
      },
      {
        id: "palette-3",
        name: "Dark Manuscript",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "photo-collage",
    title: "Photo Collage Grid",
    description: "Vintage Polaroid collage grid with 3 slots and editorial captions.",
    category: "Photo Collage",
    domainRecommended: ["Design", "Marketing", "Product"],
    defaultData: {
      title: "Workspace & Offsite Notes",
      subtitle: "Autumn Creative Retreat // Lisbon 2026",
      image1: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80",
      caption1: "Studio morning session",
      image2: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&auto=format&fit=crop&q=80",
      caption2: "Design sprint whiteboard",
      image3: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80",
      caption3: "Team demo celebrations",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Warm Polaroid",
        bg: "bg-[#EDE6DA]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Gallery",
        bg: "bg-[#F6EFD9]",
        text: "text-[#0B1F66]",
        accent: "text-[#1F4BD8]",
        border: "border-[#D1E0F5]",
      },
      {
        id: "palette-3",
        name: "Dark Room",
        bg: "bg-[#0E0F14]",
        text: "text-[#F1EBDD]",
        accent: "text-[#4FD1B5]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "milestone-poster",
    title: "Milestone Poster",
    description: "Started new role, promotion, or certification with bold numerals and confetti badge.",
    category: "Milestones",
    domainRecommended: ["Software Engineering", "Finance", "Healthcare", "Design"],
    defaultData: {
      milestoneType: "NEW CHAPTER",
      headline: "Starting as Staff Product Designer",
      organization: "Linear Labs",
      badgeNumber: "01",
      reflection: "Grateful for 4 incredible years with the team. Excited to dive into systems architecture and next-gen workflows.",
      dateLabel: "OCTOBER 2026",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Terracotta Festive",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#B5552F]/40",
      },
      {
        id: "palette-2",
        name: "Cobalt Royal",
        bg: "bg-[#1F4BD8]",
        text: "text-[#F6EFD9]",
        accent: "text-[#F2674A]",
        border: "border-[#9CC4F2]",
      },
      {
        id: "palette-3",
        name: "Midnight Prestige",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#E8A94A]/40",
      },
    ],
  },
  {
    id: "hiring-poster",
    title: "Hiring Poster",
    description: "Bold color-blocked card for open roles, domain badge, perks, and apply CTA.",
    category: "Job Posts",
    domainRecommended: ["Software Engineering", "Marketing", "Data & AI", "Sales"],
    defaultData: {
      tag: "WE ARE HIRING",
      role: "Lead Full-Stack Engineer",
      company: "Orbit Core Team",
      location: "San Francisco, CA / Remote",
      compensation: "$175k – $225k + 0.5% Equity",
      perks: "• Async-first • Annual retreat • Home office budget",
      applyEmail: "careers@orbit.test",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Mustard Block",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Signal",
        bg: "bg-[#0B1F66]",
        text: "text-[#F6EFD9]",
        accent: "text-[#1F4BD8]",
        border: "border-[#9CC4F2]",
      },
      {
        id: "palette-3",
        name: "Midnight Teal",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#4FD1B5]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "tip-of-day",
    title: "Tip of the Day",
    description: "Numbered practical tips with hand-drawn style badges and summary takeaway.",
    category: "Tips & Threads",
    domainRecommended: ["Software Engineering", "Product", "Data & AI"],
    defaultData: {
      tipNumber: "TIP #28",
      domain: "ENGINEERING CRAFT",
      title: "3 Rules for Flawless Server State Sync",
      tip1: "1. Treat server response as immutable source of truth.",
      tip2: "2. Rollback optimistic changes with graceful toast undo.",
      tip3: "3. Debounce socket broadcast events to prevent frame drops.",
      keyInsight: "Fast UI feels magical, but correct UI builds trust.",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Olive Editorial",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#6F7B4A]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Crisp",
        bg: "bg-[#F6EFD9]",
        text: "text-[#0B1F66]",
        accent: "text-[#1F4BD8]",
        border: "border-[#D1E0F5]",
      },
      {
        id: "palette-3",
        name: "Midnight Slate",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "carousel-deck",
    title: "Carousel Slide Deck",
    description: "Swipeable 5-slide mini presentation with progress dots and slide exporter.",
    category: "Carousel",
    domainRecommended: ["Marketing", "Design", "Product"],
    defaultData: {
      totalSlides: 4,
      currentSlide: 0,
      slides: [
        {
          slideNumber: "01",
          headline: "How to Build a Domain-First Network",
          body: "Why generic feeds fail and domain-specialized communities thrive in 2026.",
        },
        {
          slideNumber: "02",
          headline: "The Power of High-Signal Circles",
          body: "When designers talk to designers and engineers talk to engineers, relevance shoots to 94%.",
        },
        {
          slideNumber: "03",
          headline: "Visual Craft as a Competitive Advantage",
          body: "Editorial layouts turn dry status updates into magazine-quality portfolios.",
        },
        {
          slideNumber: "04",
          headline: "Summary & Action Steps",
          body: "Pick your domain, craft your templates, and publish work that stands out.",
        },
      ],
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Paper Craft",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Waves",
        bg: "bg-[#1F4BD8]",
        text: "text-[#F6EFD9]",
        accent: "text-[#9CC4F2]",
        border: "border-[#9CC4F2]/30",
      },
      {
        id: "palette-3",
        name: "Midnight Orbit",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#4FD1B5]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "styled-poll",
    title: "Editorial Poll Card",
    description: "Styled poll with interactive vote bars and percentage meters.",
    category: "Polls",
    domainRecommended: ["Software Engineering", "Design", "Marketing"],
    defaultData: {
      question: "Which CSS paradigm are you betting on for large-scale apps in 2026?",
      domain: "FRONTEND SURVEY",
      totalVotes: 842,
      options: [
        { label: "Tailwind CSS + Tokens", percent: 58, votes: 488 },
        { label: "CSS Modules / Vanilla", percent: 22, votes: 185 },
        { label: "StyleX / Zero-runtime", percent: 20, votes: 169 },
      ],
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Warm Editorial",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Grid",
        bg: "bg-[#F6EFD9]",
        text: "text-[#0B1F66]",
        accent: "text-[#1F4BD8]",
        border: "border-[#D1E0F5]",
      },
      {
        id: "palette-3",
        name: "Midnight Amber",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "before-after",
    title: "Before / After Slider",
    description: "Interactive draggable comparison slider showcasing redesigns or architectural refactors.",
    category: "Reviews",
    domainRecommended: ["Design", "Software Engineering"],
    defaultData: {
      title: "Component Library Redesign",
      subtitle: "Migrating from corporate blue feed to editorial paper aesthetic",
      beforeLabel: "BEFORE (2024)",
      beforeDesc: "Standard flat cards, low contrast, generic layout",
      afterLabel: "AFTER (2026)",
      afterDesc: "Fraunces typography, tactile paper textures, custom templates",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Terracotta Split",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Coast",
        bg: "bg-[#F6EFD9]",
        text: "text-[#0B1F66]",
        accent: "text-[#1F4BD8]",
        border: "border-[#D1E0F5]",
      },
      {
        id: "palette-3",
        name: "Midnight Contrast",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#4FD1B5]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "event-invite",
    title: "Event & Meetup Invite",
    description: "Editorial date block, location badge, speakers list, and RSVP button.",
    category: "Announcements",
    domainRecommended: ["Design", "Software Engineering", "Education"],
    defaultData: {
      tag: "COMMUNITY GATHERING",
      title: "Orbit Design & Engineering Salon",
      dateDay: "24",
      dateMonth: "OCT",
      time: "6:30 PM — 9:30 PM PST",
      location: "Mission District, SF + Live Stream",
      speakers: "Aarav Chen (Orbit), Meera Patel (Studio 9)",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Terracotta Calendar",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Invite",
        bg: "bg-[#0B1F66]",
        text: "text-[#F6EFD9]",
        accent: "text-[#F2674A]",
        border: "border-[#9CC4F2]",
      },
      {
        id: "palette-3",
        name: "Midnight Stage",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "case-study",
    title: "Case Study Snapshot",
    description: "Key metrics callouts (+180%, 3.4x) with mini progress bars and methodology notes.",
    category: "Announcements",
    domainRecommended: ["Product", "Marketing", "Data & AI"],
    defaultData: {
      tag: "CASE STUDY",
      title: "Scaling Realtime Sync to 100k Concurrent Nodes",
      metric1: "+180%",
      metric1Label: "Throughput Efficiency",
      metric2: "3.4x",
      metric2Label: "Faster Event Delivery",
      metric3: "99.99%",
      metric3Label: "Uptime Reliability",
      summary: "Migrated to WebSocket room partitioning and Redis streaming pipelines, cutting memory overhead by half.",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Terracotta Data",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Metric",
        bg: "bg-[#1F4BD8]",
        text: "text-[#F6EFD9]",
        accent: "text-[#9CC4F2]",
        border: "border-[#9CC4F2]/30",
      },
      {
        id: "palette-3",
        name: "Midnight Analytics",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#4FD1B5]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "weekly-reflection",
    title: "Weekly Reflection",
    description: "Journal-style card with Wins, Blockers, and Reading List entries.",
    category: "Reviews",
    domainRecommended: ["Product", "Design", "Software Engineering"],
    defaultData: {
      issueTitle: "WEEK 41 // LOGBOOK",
      dateRange: "Oct 01 – Oct 07, 2026",
      wins: "Shipped Post Template Studio; finalized 3 theme palettes.",
      blockers: "Resolving nested SVG filters across mobile WebKit.",
      reading: "'The Shape of Design' by Frank Chimero",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Parchment Journal",
        bg: "bg-[#EDE6DA]",
        text: "text-[#1E1B16]",
        accent: "text-[#6F7B4A]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Ledger",
        bg: "bg-[#F6EFD9]",
        text: "text-[#0B1F66]",
        accent: "text-[#1F4BD8]",
        border: "border-[#D1E0F5]",
      },
      {
        id: "palette-3",
        name: "Midnight Diary",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "question-card",
    title: "Question to Network",
    description: "Large bold inquiry badge designed to spark thoughtful replies and thread debates.",
    category: "Quotes",
    domainRecommended: ["Software Engineering", "Product", "Design", "Finance"],
    defaultData: {
      tag: "COMMUNITY QUESTION",
      question: "What is the single most underrated engineering decision you made that saved months of work later?",
      context: "Share your architecture wins, tooling choices, or organizational principles below.",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Mustard Inquiry",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#D9A441]",
        border: "border-[#D9A441]/40",
      },
      {
        id: "palette-2",
        name: "Cobalt Voice",
        bg: "bg-[#1F4BD8]",
        text: "text-[#F6EFD9]",
        accent: "text-[#F2674A]",
        border: "border-[#9CC4F2]",
      },
      {
        id: "palette-3",
        name: "Midnight Spark",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "resource-list",
    title: "Resource List (5 Tools)",
    description: "Curated toolkit list with numbered badges, descriptions, and tags.",
    category: "Tips & Threads",
    domainRecommended: ["Software Engineering", "Design", "Marketing"],
    defaultData: {
      title: "5 Tools I Rely On Every Day as a Tech Lead",
      category: "TOOLKIT CURATION",
      items: [
        { name: "Biome", desc: "Lightning fast linter and formatter" },
        { name: "Prisma Studio", desc: "Visual SQLite inspection" },
        { name: "Socket.IO", desc: "Bidirectional real-time pipelines" },
        { name: "Framer Motion", desc: "Fluid springs and layout transitions" },
      ],
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Paper Catalog",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt List",
        bg: "bg-[#F6EFD9]",
        text: "text-[#0B1F66]",
        accent: "text-[#1F4BD8]",
        border: "border-[#D1E0F5]",
      },
      {
        id: "palette-3",
        name: "Midnight Stack",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#4FD1B5]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "portfolio-showcase",
    title: "Portfolio Showcase",
    description: "Hero mockup slot with project tags, impact metrics, and case study highlights.",
    category: "Announcements",
    domainRecommended: ["Design", "Software Engineering"],
    defaultData: {
      tag: "CASE STUDY RELEASE",
      projectTitle: "Orbit – Editorial Network UI",
      role: "Lead Interface Architect",
      heroImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
      stats: "03 Themes • 16 Templates • <100ms Latency",
      summary: "A complete reimagination of professional identity away from stale blue feeds into warm, magazine-quality portfolios.",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Warm Gallery",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#CFC5B3]",
      },
      {
        id: "palette-2",
        name: "Cobalt Showcase",
        bg: "bg-[#0B1F66]",
        text: "text-[#F6EFD9]",
        accent: "text-[#1F4BD8]",
        border: "border-[#9CC4F2]",
      },
      {
        id: "palette-3",
        name: "Midnight Exhibition",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
  {
    id: "thank-you-card",
    title: "Thank You & Shoutout",
    description: "Tag a peer or mentor with vintage stamp badges and warm gratitude notes.",
    category: "Milestones",
    domainRecommended: ["Design", "Software Engineering", "Product", "Marketing"],
    defaultData: {
      badgeText: "KUDOS & APPRECIATION",
      recipientName: "Meera Patel",
      recipientRole: "Senior Product Designer",
      message: "Huge shoutout for leading the design system overhaul. The Fraunces typography and warm paper tokens feel unbelievable.",
      authorSignature: "— Aarav Chen",
      themeVariant: "palette-1",
    },
    colorPalettes: [
      {
        id: "palette-1",
        name: "Terracotta Warmth",
        bg: "bg-[#F7F2E9]",
        text: "text-[#1E1B16]",
        accent: "text-[#B5552F]",
        border: "border-[#B5552F]/40",
      },
      {
        id: "palette-2",
        name: "Cobalt Celebration",
        bg: "bg-[#1F4BD8]",
        text: "text-[#F6EFD9]",
        accent: "text-[#F2674A]",
        border: "border-[#9CC4F2]",
      },
      {
        id: "palette-3",
        name: "Midnight Spark",
        bg: "bg-[#171922]",
        text: "text-[#F1EBDD]",
        accent: "text-[#E8A94A]",
        border: "border-[#2A2D3A]",
      },
    ],
  },
];
